preset = "gruvbox"

[colors]
border = "#928374"            # Gray
status_line_bg = "#282828"    # Dark 0
status_line_fg = "#ebdbb2"    # Light 1

# Highlight
selected_background = "#3c3836"
selected_foreground = "#fabd2f" # Yellow

# Semantic
easy = "#b8bb26"    # Green
medium = "#fe8019"  # Orange
hard = "#fb4934"    # Red
